### ISSUE TITLE
Error on running test

### ISSUE THREAD

**Issue by ozzyozbourne** [jetzig-framework/zmd#3]
Hello, I am using zig version 13 and on running the "zig build test" command I get the error -> 

src/zmd/Node.zig:82:10: error: no field named 'fn' in enum '@typeInfo(builtin.Type).Union.tag_type.?'
        .@"fn" => Formatter{ .function = &formatter },
        
The full error log is present in the attachment error_log.txt

[error_log.txt](https://github.com/user-attachments/files/17690561/error_log.txt)

**Comment by bobf** [comment]
Hi, @ozzyozbourne , you need to use a more recent version of Zig, the `Type` enum was modified to use e.g. `fn` instead of `Fn`.

You can also try using an older version of Zmd if you like. This commit should work on .0.13:

https://github.com/jetzig-framework/zmd/commit/a197906b017d2a2d6c1896d77c04a74b13ddfa7f
